name: Create package
on: [push]
jobs:
  buildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup java"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: "Run maven package"
        run: mvn -DskipTests package
      - run: ls -la target/
      - run: mv target/*.jar target/app.jar
